// generated by cdk-dasm at 2020-01-15T15:10:28.346Z

import { Stack, StackProps, Construct, Fn } from '@aws-cdk/core';
import dynamodb = require('@aws-cdk/aws-dynamodb');

export class MyStack extends Stack {
    constructor(scope: Construct, id: string, props: StackProps = {}) {
        super(scope, id, props);
        new dynamodb.CfnTable(this, 'myDynamoDBTable', {
            attributeDefinitions: [
              {
                "attributeName": {
                  "Ref": "HashKeyElementName"
                },
                "attributeType": {
                  "Ref": "HashKeyElementType"
                }
              }
            ],
            keySchema: [
              {
                "attributeName": {
                  "Ref": "HashKeyElementName"
                },
                "keyType": "HASH"
              }
            ],
            provisionedThroughput: {
              "readCapacityUnits": {
                "Ref": "ReadCapacityUnits"
              },
              "writeCapacityUnits": {
                "Ref": "WriteCapacityUnits"
              }
            },
        });
    }
}
