#!/usr/bin/env sh
#
# Usage: ./cdkd <aws-profile-name> <ls|synth|diff|deploy|destroy> <stack-names>
# 
# Examples:
# - synthsize all stacks: ./cdkd my-profile synth \'*\'
# - list stacks:./cdkd my-profile ls 
#
export AWS_PROFILE=$1
export CDK_COMMAND=$2
shift
shift 
CDK_STACKS=$@

echo $STACKS

export AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id)"
export AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key)"
export AWS_DEFAULT_REGION="$(aws configure get region)"

echo "- AWS_PROFILE=$AWS_PROFILE"
echo "  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
echo "  AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY|tr '[:print:]' '*')"
echo "  AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"

docker run --rm -it -v $(pwd):/app -w /app \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
    robertd/alpine-aws-cdk /bin/sh -c "cdk --app 'npx ts-node bin/lambda-edge-multi-stack.ts' $CDK_COMMAND $CDK_STACKS"
